import Link from "next/link";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/kiosks">Kiosks</Link>
            <Link href="/about">About</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  );
}
